version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
  s3dav:
    build: .
    ports:
      - 8080:8080
    command: --endpoint minio:9000 --allow-buckets-ops
